import React, {useState, useEffect} from 'react'
import { getBulkBlockDeals } from '../../http/news/bulk&block_deals';
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";
import { NavLink } from 'react-router-dom';

const fetchBulkBlockDeals = async ({ symbol }) => {
  const response = await getBulkBlockDeals({ symbol });
  return response;
};

function BulkBlock({ instrument }) {
  const [deals, setDeals] = useState<{ headers: any[]; rows: any[] }>({
    headers: [],
    rows: [],
  });
  useEffect(() => {
    //   const response = fetchBulkBlockDeals({ symbol: instrument.DisplayName });
    const response = {
      head: {
        status: "0",
        statusDescription: "Success",
        responseCode: "Trendlyne",
      },
      body: {
        isCurtail: false,
        curtailMsg: "",
        stockHeaders: [
          {
            unique_name: "get_full_name",
            type: "string",
            name: "Stock Name",
          },
          {
            unique_name: "NSEcode",
            type: "string",
            name: "NSE Symbol",
          },
          {
            unique_name: "BSEcode",
            type: "string",
            name: "BSEcode",
          },
          {
            name: "Stock ID",
            type: "number",
            unique_name: "stock_id",
          },
          {
            name: "Page type",
            type: "string",
            unique_name: "page_type",
          },
          {
            unique_name: "ISIN",
            type: "string",
            name: "isin",
          },
          {
            unique_name: "default_exchange",
            type: "string",
            name: "Default Exchange",
          },
        ],
        stockData: [
          "Infosys Ltd.",
          "INFY",
          "500209",
          630,
          "Equity",
          "INE009A01021",
          "NSE",
        ],
        tableData: [
          [
            "ISHARES CORE MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2022-10-03",
            1413.45,
            4255566,
            0.10142,
            "NSE",
          ],
          [
            "ISHARES CORE EMERGING MARKETS MAURITIUS CO",
            "Block",
            "Sell",
            "2022-10-03",
            1413.45,
            4255566,
            0.10142,
            "NSE",
          ],
          [
            "ISHARES CORE MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2022-09-19",
            1377.05,
            2992931,
            0.071328,
            "BSE",
          ],
          [
            "ISHARES CORE EMERGING MARKETS MAURITIUS CO",
            "Block",
            "Sell",
            "2022-09-19",
            1377.05,
            2992931,
            0.071328,
            "BSE",
          ],
          [
            "INCOME INSURANCE LIMITED",
            "Block",
            "Purchase",
            "2022-09-01",
            1456.4,
            246859,
            0.005883,
            "BSE",
          ],
          [
            "INCOME INSURANCE LIMITED",
            "Block",
            "Purchase",
            "2022-09-01",
            1456.4,
            8154,
            0.000194,
            "BSE",
          ],
          [
            "NTUC INCOME INSURANCE CO-OPERATIVE LIMITED",
            "Block",
            "Sell",
            "2022-09-01",
            1456.4,
            246859,
            0.005883,
            "BSE",
          ],
          [
            "NTUC INCOME INSURANCE CO OPERATIVE LIMITED",
            "Block",
            "Sell",
            "2022-09-01",
            1456.4,
            8154,
            0.000194,
            "BSE",
          ],
          [
            "ISHARES MSCI INDIA ETF",
            "Block",
            "Purchase",
            "2022-08-08",
            1616.65,
            3974215,
            0.094714,
            "NSE",
          ],
          [
            "ISHARES INDIA 50 ETF",
            "Block",
            "Purchase",
            "2022-08-08",
            1616.65,
            577172,
            0.013755,
            "NSE",
          ],
          [
            "ISHARES INDIA INDEX MAURITIUS COMPANY",
            "Block",
            "Sell",
            "2022-08-08",
            1616.65,
            3974215,
            0.094714,
            "NSE",
          ],
          [
            "ISHARES INDIA MAURITIUS CO",
            "Block",
            "Sell",
            "2022-08-08",
            1616.65,
            577172,
            0.013755,
            "NSE",
          ],
          [
            "ISHARES MSCI INDIA ETF",
            "Block",
            "Purchase",
            "2022-07-25",
            1506.3,
            3974214,
            0.094714,
            "NSE",
          ],
          [
            "ISHARES INDIA 50 ETF",
            "Block",
            "Purchase",
            "2022-07-25",
            1506.3,
            577171,
            0.013755,
            "NSE",
          ],
          [
            "ISHARES INDIA INDEX MAURITIUS COMPANY",
            "Block",
            "Sell",
            "2022-07-25",
            1506.3,
            3974214,
            0.094714,
            "NSE",
          ],
          [
            "ISHARES INDIA MAURITIUS CO",
            "Block",
            "Sell",
            "2022-07-25",
            1506.3,
            577171,
            0.013755,
            "NSE",
          ],
          [
            "ISHARES MSCI INDIA ETF",
            "Block",
            "Purchase",
            "2022-07-18",
            1430.35,
            3998106,
            0.095284,
            "BSE",
          ],
          [
            "ISHARES INDIA 50 ETF",
            "Block",
            "Purchase",
            "2022-07-18",
            1430.35,
            577171,
            0.013755,
            "BSE",
          ],
          [
            "ISHARES INDIA INDEX MAURITIUS COMPANY",
            "Block",
            "Sell",
            "2022-07-18",
            1430.35,
            3998106,
            0.095284,
            "BSE",
          ],
          [
            "ISHARES INDIA MAURITIUS CO",
            "Block",
            "Sell",
            "2022-07-18",
            1430.35,
            577171,
            0.013755,
            "BSE",
          ],
          [
            "ISHARES CORE MSCI TOTAL INTERNATIONAL STOCK ETF",
            "Block",
            "Purchase",
            "2022-05-04",
            1541.0,
            3579538,
            0.085308,
            "BSE",
          ],
          [
            "ISHARES CORE TOTAL INTERNATIONAL STOCK MAURITIUS CO",
            "Block",
            "Sell",
            "2022-05-04",
            1541.0,
            3579538,
            0.085308,
            "BSE",
          ],
          [
            "ISHARES MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2021-10-20",
            1822.15,
            3141364,
            0.074866,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS INDEX MAURITIUS CO",
            "Block",
            "Sell",
            "2021-10-20",
            1822.15,
            3141364,
            0.074866,
            "BSE",
          ],
          [
            "ISHARES MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2021-10-11",
            1723.85,
            3141364,
            0.074866,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS INDEX MAURITIUS CO",
            "Block",
            "Sell",
            "2021-10-11",
            1723.85,
            3141364,
            0.074866,
            "BSE",
          ],
          [
            "ISHARES MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2021-10-04",
            1665.15,
            3229757,
            0.076972,
            "NSE",
          ],
          [
            "ISHARES EMERGING MARKETS INDEX MAURITIUS CO ",
            "Block",
            "Sell",
            "2021-10-04",
            1665.15,
            3229757,
            0.076972,
            "NSE",
          ],
          [
            "ISHARES MSCI EMERGING MARKETS ETF",
            "Block",
            "Purchase",
            "2021-09-23",
            1716.9,
            3197474,
            0.076203,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS INDEX MAURITIUS CO",
            "Block",
            "Sell",
            "2021-09-23",
            1716.9,
            3197474,
            0.076203,
            "BSE",
          ],
          [
            "TEACHER RETIREMENT SYSTEM OF TEXAS",
            "Block",
            "Purchase",
            "2021-08-31",
            1698.05,
            624289,
            0.014878,
            "BSE",
          ],
          [
            "TEACHER RETIREMENT SYSTEM OF TEXAS",
            "Block",
            "Sell",
            "2021-08-31",
            1698.05,
            417444,
            0.009949,
            "BSE",
          ],
          [
            "TEACHER RETIREMENT SYSTEM OF TEXAS",
            "Block",
            "Sell",
            "2021-08-31",
            1698.05,
            206845,
            0.00493,
            "BSE",
          ],
          [
            "GOLDMAN SACHS FUNDS GOLDMAN SACHS INDIA EQUITY PORTFOLIO",
            "Block",
            "Purchase",
            "2021-08-09",
            1650.35,
            4366150,
            0.104055,
            "BSE",
          ],
          [
            "GOLDMAN SACHS INDIA FUND LIMITED",
            "Block",
            "Sell",
            "2021-08-09",
            1650.35,
            4366150,
            0.104055,
            "BSE",
          ],
          [
            "ISHARES MSCI ALL COUNTRY ASIA EX JAPAN ETF",
            "Block",
            "Purchase",
            "2021-07-19",
            1555.45,
            1437576,
            0.034261,
            "BSE",
          ],
          [
            "ISHARES ALL COUNTRY ASIA EX JAPAN MAURITIUS CO",
            "Block",
            "Sell",
            "2021-07-19",
            1555.45,
            1437576,
            0.034261,
            "BSE",
          ],
          [
            "ISHARES MSCI ALL COUNTRY ASIA EX JAPAN ETF",
            "Block",
            "Purchase",
            "2021-07-12",
            1562.9,
            1446133,
            0.034465,
            "BSE",
          ],
          [
            "ISHARES ALL COUNTRY ASIA EX JAPAN MAURITIUS CO",
            "Block",
            "Sell",
            "2021-07-12",
            1562.9,
            1446133,
            0.034465,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS MIN VOL FACTOR ETF",
            "Block",
            "Purchase",
            "2021-06-23",
            1511.85,
            1377612,
            0.032832,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS MINIMUM VOLATILITY MAURITIUS CO",
            "Block",
            "Sell",
            "2021-06-23",
            1511.85,
            1377612,
            0.032832,
            "BSE",
          ],
          [
            "QUAESTIO SOLUTIONS FUNDS",
            "Block",
            "Purchase",
            "2021-06-16",
            1472.85,
            88433,
            0.002108,
            "BSE",
          ],
          [
            "QUAESTIO CAPITAL MANAGEMENT SGR S.P.A.-LUXEMBOURG BRANCH",
            "Block",
            "Sell",
            "2021-06-16",
            1472.85,
            88433,
            0.002108,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS MIN VOL FACTOR ETF",
            "Block",
            "Purchase",
            "2021-06-15",
            1461.8,
            1377612,
            0.032832,
            "BSE",
          ],
          [
            "ISHARES EMERGING MARKETS MINIMUM VOLATILITY MAURITIUS CO",
            "Block",
            "Sell",
            "2021-06-15",
            1461.8,
            1377612,
            0.032832,
            "BSE",
          ],
          [
            "S D SHIBULAL",
            "Block",
            "Purchase",
            "2021-05-31",
            1391.0,
            667935,
            0.015918,
            "BSE",
          ],
          [
            "KUMARI SHIBULAL",
            "Block",
            "Sell",
            "2021-05-31",
            1391.0,
            667935,
            0.015918,
            "BSE",
          ],
          [
            "S D SHIBULAL",
            "Block",
            "Purchase",
            "2021-05-27",
            1384.0,
            722545,
            0.01722,
            "BSE",
          ],
          [
            "KUMARI SHIBULAL",
            "Block",
            "Sell",
            "2021-05-27",
            1384.0,
            722545,
            0.01722,
            "BSE",
          ],
          [
            "S D SHIBULAL",
            "Block",
            "Purchase",
            "2021-05-24",
            1342.05,
            745150,
            0.017759,
            "BSE",
          ],
          [
            "KUMARI SHIBULAL",
            "Block",
            "Sell",
            "2021-05-24",
            1342.05,
            745150,
            0.017759,
            "BSE",
          ],
          [
            "S D SHIBULAL",
            "Block",
            "Purchase",
            "2021-05-19",
            1327.0,
            753580,
            0.017959,
            "BSE",
          ],
          [
            "KUMARI SHIBULAL",
            "Block",
            "Sell",
            "2021-05-19",
            1327.0,
            753580,
            0.017959,
            "BSE",
          ],
          [
            "S D SHIBULAL",
            "Block",
            "Purchase",
            "2021-05-12",
            1317.95,
            758755,
            0.018083,
            "BSE",
          ],
          [
            "KUMARI SHIBULAL",
            "Block",
            "Sell",
            "2021-05-12",
            1317.95,
            758755,
            0.018083,
            "BSE",
          ],
          [
            "ISHARES MSCI EMERGING MARKETS ASIA ETF",
            "Block",
            "Purchase",
            "2021-04-22",
            1351.35,
            538450,
            0.012832,
            "BSE",
          ],
          [
            "ISHARES EM ASIA MAURITIUS CO",
            "Block",
            "Sell",
            "2021-04-22",
            1351.35,
            538450,
            0.012832,
            "BSE",
          ],
          [
            "THE MTBJ LTD. AS TRST FOR GOVERNMENT PENSION INVESTMENT FUND MTBJ400045849",
            "Block",
            "Purchase",
            "2021-04-08",
            1430.25,
            1578246,
            0.037613,
            "BSE",
          ],
          [
            "THE MTBJ LTD. AS TRST FOR GOVRNMNT PENSION INVSTMNT FUND MUTB400045794",
            "Block",
            "Sell",
            "2021-04-08",
            1430.25,
            1578246,
            0.037613,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2021-03-04",
            1339.6,
            1127159,
            0.026863,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2021-03-04",
            1339.6,
            1127159,
            0.026863,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2021-02-25",
            1276.8,
            1280101,
            0.030508,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2021-02-25",
            1276.8,
            1280101,
            0.030508,
            "BSE",
          ],
          [
            "GS INDIA EQUITY",
            "Block",
            "Purchase",
            "2021-02-08",
            1272.3,
            247068,
            0.005888,
            "BSE",
          ],
          [
            "ALLIANZ GL INV GMBH ACTING ON BEHALF OF ALLIANZGI-FONDS GS INDIA EQUITY",
            "Block",
            "Sell",
            "2021-02-08",
            1272.3,
            247068,
            0.005888,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2021-02-04",
            1288.0,
            1350587,
            0.032187,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2021-02-04",
            1288.0,
            1350587,
            0.032187,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2021-01-28",
            1288.75,
            1190428,
            0.028371,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2021-01-28",
            1288.75,
            1190428,
            0.028371,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2021-01-14",
            1373.85,
            1220101,
            0.029078,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2021-01-14",
            1373.85,
            1220101,
            0.029078,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-12-03",
            1138.45,
            1300217,
            0.030987,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-12-03",
            1138.45,
            1300217,
            0.030987,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-11-13",
            1118.8,
            1394872,
            0.033243,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-11-13",
            1118.8,
            1394872,
            0.033243,
            "BSE",
          ],
          [
            "ISHARES MSCI BRIC ETF",
            "Block",
            "Purchase",
            "2020-11-10",
            1136.2,
            238875,
            0.005693,
            "BSE",
          ],
          [
            "ISHARES BRIC INDEX MAURITIUS CO",
            "Block",
            "Sell",
            "2020-11-10",
            1136.2,
            238875,
            0.005693,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-10-28",
            1090.0,
            1411217,
            0.033632,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-10-28",
            1090.0,
            1411217,
            0.033632,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-10-15",
            1147.45,
            1431086,
            0.034106,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-10-15",
            1147.45,
            1431086,
            0.034106,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-09-30",
            1003.9,
            1456065,
            0.034701,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-09-30",
            1003.9,
            1456065,
            0.034701,
            "BSE",
          ],
          [
            "VFTR C INSTITUTIONAL TOTAL INTERNATIONAL STOCK MARKET INDEX TRUST II",
            "Block",
            "Purchase",
            "2020-09-02",
            918.75,
            1436855,
            0.034243,
            "BSE",
          ],
          [
            "VANGUARD TOTAL INTERNATIONAL STOCK INDEX FUND",
            "Block",
            "Sell",
            "2020-09-02",
            918.75,
            1436855,
            0.034243,
            "BSE",
          ],
          [
            "BOFA SECURITIES EUROPE SA",
            "Block",
            "Purchase",
            "2020-08-05",
            949.85,
            191799,
            0.004571,
            "BSE",
          ],
          [
            "MERRILL LYNCH MARKETS SINGAPORE PTE LTD",
            "Block",
            "Sell",
            "2020-08-05",
            949.85,
            191799,
            0.004571,
            "BSE",
          ],
          [
            "VAERDIPAPIRFONDEN NORDEA INVEST PORTEFOLJE AKTIER",
            "Block",
            "Purchase",
            "2020-06-16",
            687.55,
            298121,
            0.007105,
            "BSE",
          ],
          [
            "INVESTERINGSFORENINGEN NORDEA INVEST PORTEFOLJE",
            "Block",
            "Sell",
            "2020-06-16",
            687.55,
            298121,
            0.007105,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-03-17",
            581.0,
            190000,
            0.004528,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-03-17",
            581.0,
            190000,
            0.004528,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-03-12",
            648.0,
            400000,
            0.009533,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-03-12",
            648.0,
            400000,
            0.009533,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-03-09",
            701.0,
            203000,
            0.004838,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-03-09",
            701.0,
            203000,
            0.004838,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-03-06",
            740.0,
            180000,
            0.00429,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-03-06",
            740.0,
            180000,
            0.00429,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-03-04",
            753.0,
            240000,
            0.00572,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-03-04",
            753.0,
            240000,
            0.00572,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-02-28",
            740.0,
            200000,
            0.004766,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-02-28",
            740.0,
            200000,
            0.004766,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-02-24",
            805.0,
            150000,
            0.003575,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-02-24",
            805.0,
            150000,
            0.003575,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-02-20",
            799.5,
            187395,
            0.004466,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-02-20",
            799.5,
            187395,
            0.004466,
            "BSE",
          ],
          [
            "BLACKROCK GLOBAL FUNDS INDIA FUND",
            "Block",
            "Purchase",
            "2020-02-14",
            788.0,
            288000,
            0.006864,
            "BSE",
          ],
          [
            "MERRILL LYNCH INDIA EQUITIES FUND (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2020-02-14",
            788.0,
            288000,
            0.006864,
            "BSE",
          ],
          [
            "JANUS HENDERSON INTERNATIONAL OPPORTUNITIES FUND",
            "Block",
            "Purchase",
            "2019-04-01",
            744.0,
            1472881,
            0.035102,
            "BSE",
          ],
          [
            "JANUS HENDERSON EMERGING MARKETS FUND",
            "Block",
            "Purchase",
            "2019-04-01",
            744.0,
            126635,
            0.003018,
            "BSE",
          ],
          [
            "HENDERSON GLOBAL TECHNOLOGY FUND A SERIES OF HENDERSON GLOBAL FUNDS",
            "Block",
            "Sell",
            "2019-04-01",
            744.0,
            1472881,
            0.035102,
            "BSE",
          ],
          [
            "HENDERSON EMG MKTS OPPORTUNITIES FUND A SERIES OF HENDERSON GLOBAL FUNDS",
            "Block",
            "Sell",
            "2019-04-01",
            744.0,
            126635,
            0.003018,
            "BSE",
          ],
          [
            "JANUS HENDERSON GLOBAL SUSTAINABLE EQUITY FUND",
            "Block",
            "Purchase",
            "2019-03-25",
            740.0,
            1599516,
            0.03812,
            "BSE",
          ],
          [
            "HENDERSON GLOBAL TECHNOLOGY FUND A SERIES OF HENDERSON GLOBAL FUNDS",
            "Block",
            "Sell",
            "2019-03-25",
            740.0,
            1472881,
            0.035102,
            "BSE",
          ],
          [
            "HENDERSON EMG MKTS OPPORTUNITIES FUND A SERIES OF HENDERSON GLOBAL FUNDS",
            "Block",
            "Sell",
            "2019-03-25",
            740.0,
            126635,
            0.003018,
            "BSE",
          ],
          [
            "POWERSHARES INDIA PORTFOLIO",
            "Block",
            "Purchase",
            "2019-03-22",
            738.95,
            1727935,
            0.041181,
            "NSE",
          ],
          [
            "POWERSHARES MAURITIUS (PINSPV) (679038)",
            "Block",
            "Sell",
            "2019-03-22",
            738.95,
            1727935,
            0.041181,
            "NSE",
          ],
          [
            "TRUSTEES OF THE ESTATE OF BERNICE PAUAHI BISHOP DBA KAMEHAM",
            "Block",
            "Purchase",
            "2019-02-25",
            734.95,
            1263230,
            0.030106,
            "NSE",
          ],
          [
            "TRUSTEES OF THE ESTATE OF BERNICE PAUAHI BISHOP DBA KAMEHAM",
            "Block",
            "Sell",
            "2019-02-25",
            734.95,
            1263230,
            0.030106,
            "NSE",
          ],
          [
            "SOCIETE GENERALE",
            "Block",
            "Purchase",
            "2017-12-19",
            1012.5,
            1584613,
            0.037765,
            "BSE",
          ],
          [
            "MORGAN STANLEY FRANCE SAS",
            "Block",
            "Sell",
            "2017-12-19",
            1012.5,
            1584613,
            0.037765,
            "BSE",
          ],
          [
            "NATWEST BANK PLC AS TRUSTEE OF THE JUPITER INDIA FUND",
            "Block",
            "Purchase",
            "2017-06-22",
            950.0,
            66291,
            0.00158,
            "BSE",
          ],
          [
            "JUPEITER SOUTH ASIA INVESTMENT COMPANY LIMITED",
            "Block",
            "Sell",
            "2017-06-22",
            950.0,
            66291,
            0.00158,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FUNDS INDIAN EQUITY",
            "Block",
            "Purchase",
            "2016-09-26",
            1040.0,
            310000,
            0.007388,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FUNDS GLOBAL EMERGING MARKETS EQUITY",
            "Block",
            "Purchase",
            "2016-09-26",
            1040.0,
            82037,
            0.001955,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FU NDS MAURITIUS LTD",
            "Block",
            "Sell",
            "2016-09-26",
            1040.0,
            310000,
            0.007388,
            "BSE",
          ],
          [
            "HSBC GIF MAURITIUS NO 2 LIMITED",
            "Block",
            "Sell",
            "2016-09-26",
            1040.0,
            82037,
            0.001955,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FUNDS INDIAN EQUITY",
            "Block",
            "Purchase",
            "2016-09-19",
            1050.0,
            435000,
            0.010367,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FU NDS MAURITIUS LTD",
            "Block",
            "Sell",
            "2016-09-19",
            1050.0,
            435000,
            0.010367,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FUNDS INDIAN EQUITY",
            "Block",
            "Purchase",
            "2016-08-08",
            1067.4,
            899177,
            0.021429,
            "BSE",
          ],
          [
            "HSBC GLOBAL INVESTMENT FU NDS MAURITIUS LTD",
            "Block",
            "Sell",
            "2016-08-08",
            1067.4,
            899177,
            0.021429,
            "BSE",
          ],
          [
            "NADATHUR SRINIVASA RAGHAVAN",
            "Block",
            "Purchase",
            "2016-04-01",
            1220.15,
            578279,
            0.013782,
            "NSE",
          ],
          [
            "JAMUNA RAGHAVAN",
            "Block",
            "Purchase",
            "2016-04-01",
            1220.25,
            196721,
            0.004688,
            "NSE",
          ],
          [
            "ANAND NADATHUR",
            "Block",
            "Sell",
            "2016-04-01",
            1220.18,
            775000,
            0.01847,
            "NSE",
          ],
          [
            "NEW INDIA INVESTMENT TRUST PLC",
            "Block",
            "Purchase",
            "2016-02-15",
            1083.5,
            1338400,
            0.031897,
            "BSE",
          ],
          [
            "NEW INDIA INVESTMENT COMPANY MAURITIUS LIMITED",
            "Block",
            "Sell",
            "2016-02-15",
            1083.5,
            1338400,
            0.031897,
            "BSE",
          ],
          [
            "MERCER QIF FUND PLC - MERCER INVESTMENT FUND 1",
            "Block",
            "Purchase",
            "2015-04-24",
            2136.1,
            632000,
            0.015062,
            "NSE",
          ],
          [
            "THE LOCAL GOVERNMENT PENSIONS INSTITUTION A/C THE LOCAL GOV",
            "Block",
            "Sell",
            "2015-04-24",
            2136.1,
            632000,
            0.015062,
            "NSE",
          ],
          [
            "DB INTERNATIONAL ASIA LIMITED",
            "Bulk",
            "Purchase",
            "2014-12-08",
            1987.85,
            15556631,
            0.370749,
            "NSE",
          ],
          [
            "AKSHATA MURTHY",
            "Bulk",
            "Sell",
            "2014-12-08",
            1988.55,
            6000000,
            0.142993,
            "NSE",
          ],
          [
            "NANDAN MOHAN NILEKANI",
            "Bulk",
            "Sell",
            "2014-12-08",
            1988.51,
            6000000,
            0.142993,
            "NSE",
          ],
          [
            "ROHINI NILEKANI",
            "Bulk",
            "Sell",
            "2014-12-08",
            1988.55,
            6000000,
            0.142993,
            "NSE",
          ],
          [
            "LIBERTY MUTUAL RETIREMENT PLAN MASTER TRUST",
            "Block",
            "Purchase",
            "2013-02-01",
            2785.0,
            25258,
            0.000602,
            "BSE",
          ],
          [
            "MICM-LIBRTY LIFE ASUR CO BOSTON NEWPORT TIGER",
            "Block",
            "Sell",
            "2013-02-01",
            2785.0,
            25258,
            0.000602,
            "BSE",
          ],
          [
            "THE ROYAL BANK OF SCOTLAND ASIA MERCHANT BANK SINGAPORE LT",
            "Block",
            "Purchase",
            "2012-11-06",
            2391.5,
            329090,
            0.007843,
            "BSE",
          ],
          [
            "ABN AMRO BANK NV",
            "Block",
            "Sell",
            "2012-11-06",
            2391.5,
            329090,
            0.007843,
            "BSE",
          ],
          [
            "THE ROYAL BANK OF SCOTLAND ASIA MERCHANT BANK SINGAPORE LT",
            "Block",
            "Purchase",
            "2012-10-25",
            2340.5,
            150000,
            0.003575,
            "BSE",
          ],
          [
            "ABN AMRO BANK NV",
            "Block",
            "Sell",
            "2012-10-25",
            2340.5,
            150000,
            0.003575,
            "BSE",
          ],
          [
            "ISHARES MSCI INDIA MAURITIUS COMPANY",
            "Block",
            "Purchase",
            "2011-10-17",
            2745.5,
            164233,
            0.003914,
            "BSE",
          ],
          [
            "HSBC BANK (MAURITIUS) LIMITED",
            "Block",
            "Sell",
            "2011-10-17",
            2745.5,
            164233,
            0.003914,
            "BSE",
          ],
          [
            "ISHARES BSE SENSEX MAURITIUS COMPANY",
            "Block",
            "Purchase",
            "2011-09-12",
            2200.0,
            164333,
            0.003916,
            "NSE",
          ],
          [
            "THE ROYAL BANK OF SCOTLAND N.V",
            "Block",
            "Sell",
            "2011-09-12",
            2200.0,
            164333,
            0.003916,
            "NSE",
          ],
          [
            "THE ROYAL BANK OF SCOTLAND N.V.",
            "Block",
            "Purchase",
            "2010-06-18",
            2810.0,
            109000,
            0.002598,
            "BSE",
          ],
          [
            "CITIGROUP GLOBAL MARKETS MAURITIUS PRIVATE LIMITED",
            "Block",
            "Sell",
            "2010-06-18",
            2810.0,
            109000,
            0.002598,
            "BSE",
          ],
          [
            "THE ROYAL BANK OF SCOTLAND N.V.",
            "Block",
            "Purchase",
            "2010-06-11",
            2672.0,
            92258,
            0.002199,
            "BSE",
          ],
          [
            "CITIGROUP GLOBAL MARKETS MAURITIUS PRIVATE  LIMITED",
            "Block",
            "Sell",
            "2010-06-11",
            2672.0,
            92258,
            0.002199,
            "BSE",
          ],
          [
            "ABN AMRO BANK NV",
            "Block",
            "Purchase",
            "2010-06-09",
            2650.0,
            20800,
            0.000496,
            "BSE",
          ],
          [
            "CITIGROUP GLOBAL MARKETS MAURITIUS PRIVATE LIMITED",
            "Block",
            "Sell",
            "2010-06-09",
            2650.0,
            20800,
            0.000496,
            "BSE",
          ],
          [
            "SWISS FINANCE CORPORATION (MAURITIUS) LTD",
            "Block",
            "Purchase",
            "2010-01-14",
            2664.0,
            227885,
            0.005431,
            "BSE",
          ],
          [
            "CITIGROUP GLOBAL MARKETS MAURITIUS PRIVATE LIMITED",
            "Block",
            "Sell",
            "2010-01-14",
            2664.0,
            227885,
            0.005431,
            "BSE",
          ],
          [
            "CREDIT SUISSE (SINGAPORE) LIMITED A/C CREDIT SUISSE (SINGAPO",
            "Block",
            "Purchase",
            "2010-01-13",
            2619.0,
            227885,
            0.005431,
            "BSE",
          ],
          [
            "CITIGROUP GLOBAL MARKETS MAURITIUS PRIVATE LIMITED",
            "Block",
            "Sell",
            "2010-01-13",
            2619.0,
            227885,
            0.005431,
            "BSE",
          ],
          [
            "ABN AMRO BANK N V LONDON BRANCH",
            "Block",
            "Purchase",
            "2008-01-10",
            1660.0,
            356000,
            0.008484,
            "BSE",
          ],
          [
            "JF ASSET MANAGEMENT FII",
            "Block",
            "Sell",
            "2008-01-10",
            1660.0,
            356000,
            0.008484,
            "BSE",
          ],
          [
            "DSP MERRILL LYNCH CAPITAL MARKET ESPANA",
            "Block",
            "Purchase",
            "2007-01-31",
            2242.15,
            63200,
            0.001506,
            "BSE",
          ],
          [
            "BARCLAYS CAPITAL MAURITIUS LTD",
            "Block",
            "Sell",
            "2007-01-31",
            2242.15,
            63200,
            0.001506,
            "BSE",
          ],
          [
            "DEUTSCHE SECURITIES MAURITIUS LIMITED",
            "Block",
            "Purchase",
            "2007-01-24",
            2235.35,
            81000,
            0.00193,
            "BSE",
          ],
          [
            "BARCLAYS CAPITAL MAURITIUS LTD",
            "Block",
            "Sell",
            "2007-01-24",
            2235.35,
            81000,
            0.00193,
            "BSE",
          ],
          [
            "ABN AMRO BANK NV LONDON",
            "Block",
            "Purchase",
            "2006-12-01",
            2179.71,
            121292,
            0.002891,
            "BSE",
          ],
          [
            "MERILL LYNCH CAPTAL MARKETS",
            "Block",
            "Sell",
            "2006-12-01",
            2179.71,
            121292,
            0.002891,
            "BSE",
          ],
        ],
        tableHeaders: [
          {
            name: "Client Name",
            type: "string",
            unique_name: "client_name",
          },
          {
            name: "Deal Type",
            type: "string",
            unique_name: "get_deal_type_display",
          },
          {
            name: "Action",
            type: "string",
            unique_name: "get_action_display",
          },
          {
            name: "Date",
            type: "date",
            unique_name: "date",
          },
          {
            name: "Average Price",
            type: "number",
            unique_name: "price",
          },
          {
            name: "Quantity",
            type: "number",
            unique_name: "quantity",
          },
          {
            name: "%Traded",
            type: "percentage",
            unique_name: "traded_percent",
          },
          {
            name: "Exchange",
            type: "string",
            unique_name: "exchange",
          },
        ],
        extraHeaders: [],
      },
    };
    function createData(d) {
      const [
        client_name,
        deal_type,
        action,
        date,
        average_price,
        quantity,
        traded_percent,
        exchange,
      ] = d;
      // client_name: string,
      // deal_type: string,
      // action: string,
      // date: string,
      // average_price: number,
      // quantity: number,
      // traded_percent: number,
      // exchange: string,
      return {
        client_name,
        deal_type,
        action,
        date,
        average_price,
        quantity,
        traded_percent,
        exchange,
      };
    }
    const headers = response.body.tableHeaders.map((h) => h.name);
    const rows = response.body.tableData.map((d) => createData(d));
    setDeals({
      headers,
      rows,
    });
  }, []);
  return (
    <div className="border rounded-md">
      <h1 className="p-5 flex gap-4">
        <NavLink
          to="/home/bulk%20&%20block%20deals"
          className={({ isActive }) =>
            (isActive ? "text-blue font-medium" : "") + " text-lg"
          }
        >
          Bulk & Block Deals
        </NavLink>
        <NavLink
          to="/home/insider%20trades"
          className={({ isActive }) =>
            (isActive ? "text-blue font-medium" : "") + " text-lg"
          }
        >
          Insider Trades
        </NavLink>
      </h1>
      <div className="max-h-[350px] overflow-y-scroll">
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow>
                {deals.headers.map((header) => (
                  <TableCell>
                    <span className="text-xs text-primary">{header}</span>
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody sx={{ minHeight: 300 }}>
              {deals.rows.map((row, i) => (
                <TableRow
                  key={i}
                  sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                >
                  <TableCell>
                    <span className="text-base font-medium">
                      {row.client_name}
                    </span>
                  </TableCell>
                  <TableCell align="center">
                    <span className="text-base">{row.deal_type}</span>
                  </TableCell>
                  <TableCell align="center">
                    <span
                      className={`text-base ${
                        row.action === "Purchase"
                          ? "text-success"
                          : "text-failure"
                      }`}
                    >
                      {row.action}
                    </span>
                  </TableCell>
                  <TableCell align="center">
                    <span className="text-base">{row.date}</span>
                  </TableCell>
                  <TableCell align="right">
                    <span className="text-base">{row.average_price}</span>
                  </TableCell>
                  <TableCell align="center">
                    <span className="text-base">{row.quantity}</span>
                  </TableCell>
                  <TableCell align="right">
                    <span className="text-base">{row.traded_percent}</span>
                  </TableCell>
                  <TableCell align="right">
                    <span className="text-base">{row.exchange}</span>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </div>
    </div>
  );
}

export default BulkBlock