import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  instrument: {
    AGM: false,
    AllOrNone: false,
    Bonus: false,
    Dividend: false,
    EGM: false,
    AuctionDetailInfo: {
      AuctionNumber: 0,
      AuctionStatus: 0,
      InitiatorType: 0,
      SettlementPeriod: 0,
      TotalBuyQty: 0,
      TotalSellQty: 0,
      AuctionQty: 0,
      AuctionPrice: 0,
      BestBuyPrice: 0,
      BestSellPrice: 0,
    },
    ELMargin: 0,
    Interest: false,
    ISIN: "",
    MinimumFill: false,
    Rights: false,
    VaRMargin: 0,
    IssuedCapital: 0,
    BoardLotQuantity: 0,
    FaceValue: 0,
    Spread: 0,
    CallAuction1Flag: false,
    GSMIndicator: -1,
    SettlementNo: "",
    IsRollOverContract: false,
    SourceSeries: "",
    TargetSeries: "",
    ExDate: "0001-01-01T00:00:00",
    InstrumentID: 1100100026000,
    ExchangeInstrumentID: 26000,
    PreferredExchangeInstrumentID: -1,
    PreferredExchangeSegment: 0,
    OppositeExchangeInstrumentID: -1,
    OppositeExchangeSegment: 0,
    DisplayName: "NIFTY 50",
    Name: "NIFTY 50",
    AuctionNumber: 0,
    MinimumQty: 1,
    IsIndex: true,
    QuantityMultiplier: 1,
    Multiplier: 1,
    PriceNumerator: 1,
    PriceDenominator: 1,
    LotSize: 1,
    InstrumentType: 8,
    SymbolType: 0,
    CfiCode: "ESXXXX",
    Status: "",
    TicksPerPoint: 1,
    TickSize: 1,
    ByPassDPR: false,
    Description: "NIFTY 50-SPOT",
    IsImpliedMarket: false,
    IsTradeable: false,
    ExchangeSegment: 1,
    Series: "SPOT",
    MaxTradeVolume: 2147483647,
    PriceBand: {
      High: "NaN",
      Low: "NaN",
      HighString: "NA",
      LowString: "NA",
      CreditRating: "NA",
      HighExecBandString: "0.00",
      LowExecBandString: "0.00",
      HighExecBand: 0,
      LowExecBand: 0,
      TERRange: "0.00-0.00",
    },
    DecimalDisplace: 2,
    ExtendedMarketProperties: {},
    MarketTypeStatusEligibility: {},
    NameWithExchange: "NIFTY 50-NSECM",
    NameWithSeries: "NIFTY 50-SPOT",
    DisplayNameWithExchange: "NIFTY 50 - NSECM",
    DisplayNameWithSeries: "NIFTY 50 - SPOT",
    DisplayNameWithSeriesAndExchange: "NIFTY 50 - SPOT - NSECM",
    FreezeQty: 0,
    LastUpdateTime: 0,
    FiftyTwoWeekHigh: 0,
    FiftyTwoWeekLow: 0,
    Bhavcopy: {
      Open: 0,
      High: 0,
      Low: 0,
      Close: 0,
      TotTrdQty: 0,
      TotTrdVal: 0,
      TimeStamp: "0001-01-01T00:00:00",
      TotalTrades: 0,
      OpenInterest: 0,
      SettlementPrice: 0,
    },
    AdditionalPreExpiryMarginPerc: 0,
    AdditionalMarginPercLong: 0,
    AdditionalMarginPercShort: 0,
    DeliveryMarginPerc: 0,
    SpecialMarginPercBuy: 0,
    SpecialMarginPercSell: 0,
    TenderMargin: 0,
    ELMLongMargin: 0,
    ELMShortMargin: 0,
    InitialMarginPerc: 0,
    ExposureMarginPerc: 0,
    CallAuctionIndicator: 0,
    MarketType: 1,
    CurrentEligibleMarketType: 1,
    InstrumentProductType: 0,
    TotalMargin: 0,
    SettlementIndicator: "",
    Industry: 0,
  },
};

export const tvcSlice = createSlice({
  name: "tvc",
  initialState,
  reducers: {
    tvcReducer: (state, action) => {
      state.instrument = action.payload.instrument;
    },
  },
});

export const { tvcReducer } = tvcSlice.actions;

export default tvcSlice.reducer;
